---
title: "COVID Flu: Whole Blood RNA-Seq Baseline Enriched Genesets"
output:
  html_document:
    df_print: paged
    code_folding: hide
    toc: True
editor_options:
  chunk_output_type: console
---


```{r setup, message=F}
library(knitr)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(SummarizedExperiment)
library(BiocParallel)
library(doParallel)
param = SnowParam(32,"SOCK",progressbar = F)
register(param)
registerDoParallel()

source('R/utils/dream.models.R')
loadLibraries()

knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = FALSE)
opts_knit$set(echo = TRUE, message = FALSE, warning = FALSE, cache.lazy = FALSE, out.width=900)
opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache.lazy = FALSE, out.width=900)

figure.folder <- "figures"
dir.create(figure.folder)
output.folder <- file.path("output","rna-seq")
dir.create(output.folder)
output.prefix <- "bulk.rna."
```

### Import Data
Identifying enriched genesets that are stable at day -7 and day 0 (i.e. consistent in the GSEA using samples from different visits)

Pre-Vaccination combines both day -7 and day 0 samples
```{r import}
# rna-seq data
# normalized
#normalized.rna.data <- readRDS(file.path("output","rna-seq","covid_flu.normalized.rna.data.RDS"))
normalized.rna.data <- readRDS(file.path("data","covid_flu.normalized.rna.data.RDS"))
normalized.geneExpr <- assays(normalized.rna.data)$seqRUV.norm.count
rownames(normalized.geneExpr) <- rowData(normalized.rna.data)[rownames(normalized.geneExpr),]$symbol
sample.info <- as.data.frame(colData(normalized.rna.data))

# TBNK Data
tbnk.data <- read.csv(file.path("data","covid_flu.cbc.tbnk.data.csv"),check.names = F)
sample.info <- merge(sample.info,tbnk.data[,c("alt.subject.id","visit",grep("\\(%\\)$",colnames(tbnk.data),value=T))],
                     by=c("alt.subject.id","visit"),all.x=T)
rownames(sample.info) <- paste0("P",sample.info$library.plate,".",sample.info$library.well)

# GSEA
baseline.gsea.res <- read.csv(file.path(output.folder,paste0(output.prefix,"baseline.gsea.csv")))
table(baseline.gsea.res$visit,baseline.gsea.res$term)

gsea.p.treshold <- 0.05
# use adjusted p-values within or across ontologies?
use.pval <- "adj.P.Val" # intra
#use.pval <- "p.adjust" # inter

stable.de.genesets <- as.data.frame(tidyr::pivot_wider(baseline.gsea.res,id_cols=c(term,parameter,ont),
                                                       names_from=visit,values_from=c(NES,adj.P.Val)))
# sig. p values
stable.de.genesets <- stable.de.genesets[rowSums(stable.de.genesets[,paste0(use.pval,"_",unique(baseline.gsea.res$visit))] < gsea.p.treshold) == 3,]
# consistent direction
stable.de.genesets <- stable.de.genesets[abs(rowSums(sign(stable.de.genesets[,paste0("NES_",unique(baseline.gsea.res$visit))]))) == 3,]
stable.de.genesets$ID <- paste0(stable.de.genesets$term,":",stable.de.genesets$parameter)
```

### TSD-dependent Genesets
Check which of the enriched genesets are associated with TSD using module scores generated from leading edge genes
```{r tsd}
# using the combined model edge genes and both baseline and D0 timepoints to calculate spearman's rho
# edge.genes <- sapply(stable.de.genesets$core_enrichment,strsplit,"/")
# names(edge.genes) <- rownames(stable.de.genesets)
# merge same genesets from different contrasts
stable.de.genesets <- merge(stable.de.genesets,subset(baseline.gsea.res,visit == "Pre-Vaccination")[,c("term","parameter","ont","core_enrichment")],
      by=c("term","parameter","ont"))

merged.edge.genes <- aggregate(stable.de.genesets$core_enrichment,
                               list(contrast=stable.de.genesets$term,parameter=stable.de.genesets$parameter),
                               function(x){paste0(x,collapse = "/")})
edge.genes <- sapply(merged.edge.genes$x,function(x){unique(strsplit(x,"/"))})
names(edge.genes) <- paste0(merged.edge.genes$contrast,":",merged.edge.genes$parameter)
edge.genes.sample.scores <- GSVA::gsva(normalized.geneExpr,edge.genes,parallel.sz=6,min.sz=3)
tsd.associated.geneset.scores <- cbind(sample.info,t(edge.genes.sample.scores)[rownames(sample.info),])

baseline.tsd.associated.geneset.scores <- subset(tsd.associated.geneset.scores,visit %in% c("Day -7","Day 0") & 
                                          !is.na(covid.diagnosis.start.date.to.sample.drawn))
tsd.model.fit <- baseline.tsd.association.model(t(scale(apply(baseline.tsd.associated.geneset.scores[,names(edge.genes)],2,rank))),
                                               baseline.tsd.associated.geneset.scores,additional.fixed.effects = "`Neutrophils % of Parent (%)`")
tsd.model.de.res <- model.term.statistics(tsd.model.fit,grep("TSD",colnames(tsd.model.fit$coefficients),value=T))
tsd.asso.genesets <- unique(subset(tsd.model.de.res,P.Value < 0.05)$parameter)
```

### Visualization
```{r plot,fig.cap="ED. Fig. 1e"}
geneset.groups <- list("Metabolic processes"=
                         c("HALLMARK_OXIDATIVE_PHOSPHORYLATION","HALLMARK_FATTY_ACID_METABOLISM","HALLMARK_GLYCOLYSIS","HALLMARK_MTORC1_SIGNALING"),
                       "IFN signaling"=c("HALLMARK_INTERFERON_GAMMA_RESPONSE"),
                       "Innate immune activation"=c("enriched in monocytes (II) (M11.0)","cell cycle and transcription (M4.0)"),
                       "Cell cycle/Proliferation"=c("HALLMARK_G2M_CHECKPOINT","cell cycle (I) (M4.1)"),
                       "T-cell activation/differentiation"=
                         c("T cell activation (II) (M7.3)","T cell surface signature (S0)","T cell differentiation (M14)"),
                       "Neutrophils"=c("enriched in neutrophils (I) (M37.1)"))
geneset.groups <- data.frame(class=rep(names(geneset.groups),sapply(geneset.groups,length)),member=unlist(geneset.groups))

contrasts.to.plot <- c("COVR.m","COVR.f","COVR.male.v.female")
# TSD independent genesets
wholeblood.genesets <- subset(stable.de.genesets,term %in% contrasts.to.plot & 
                                      parameter %in% geneset.groups$member & !(ID %in% tsd.asso.genesets))
tsd.independent.genesets <- wholeblood.genesets
tsd.independent.genesets$geneset.group <- geneset.groups[match(tsd.independent.genesets$parameter,geneset.groups$member),"class"]
tsd.independent.genesets$geneset <- sapply(tsd.independent.genesets$parameter,
                                           function(x){paste0(strwrap(gsub("_"," ",x),width=30),collapse = "\n")})

ggplot(tsd.independent.genesets,aes(term,geneset)) + 
  geom_point(aes(fill=`NES_Pre-Vaccination`,pch=`NES_Pre-Vaccination` > 0),color="black",size=4) + 
  scale_shape_manual(values=c(25,24)) +
  scale_fill_gradientn(colors=colorRampPalette(c("#0066FF","#003399","#000066","black","yellow4","yellow"))(100),limits=c(-2.7,2.3)) + 
  scale_color_manual(values=c("white","black")) +
  xlab("Contrast") + ylab("") + ggtitle("Selected baseline state differences in whole blood") +
  theme_bw() + facet_grid(geneset.group~.,scales = "free",space = "free",switch = "y") +
  scale_y_discrete(position = "right") +
  theme(axis.text.x = element_text(angle=30,hjust=1,size=8),legend.position = "bottom",legend.box = "vertical",
        strip.background = element_rect(fill="white",color="white"),strip.text.y.left = element_text(angle=0,hjust = 1,size=8))
ggsave(file.path(figure.folder,"ED.Fig1e.pdf"),width=5,height=5.5)
```

### Session Info
```{r session}
sessionInfo()
```